server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: xxcaxxc
    url: jdbc:mysql://localhost:3306/note?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yy-MM-dd hh:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
    #redis配置
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      shutdown-timeout: 1800000
##    nacos配置
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yaml
  application:
    name: nacosTest

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


